# Copyright (C) 2014 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: goran@reciprocitylabs.com
# Maintained By: goran@reciprocitylabs.com

---
- name: install linux packages
  sudo: yes
  with_items: ggrc_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: create development directories
  sudo: yes
  with_items: ggrc_development_directories
  file:
    path: "{{ item.name }}"
    owner: vagrant
    group: vagrant
    state: directory

- name: prepare development virtualenv
  command: make setup_dev DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: copy npm package.json to dev directory
  command: cp /vagrant/package.json /vagrant-dev/package.json

- name: install npm modules
  command: npm install
  args:
    chdir: /vagrant-dev

- name: link node_modules
  file: src=/vagrant-dev/node_modules dest=/vagrant/node_modules state=link

- name: run make appengine
  command: make appengine DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: run make bower_components
  command: make bower_components DEV_PREFIX=/vagrant-dev
  args:
    chdir: /vagrant

- name: change root password
  mysql_user:
    name: root
    password: root
    login_user: root
    login_password: root
    check_implicit_admin: yes
    priv: "*.*:ALL"

- name: create databases
  with_items: ggrc_databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
    login_user: root
    login_password: root

- name: configure bash
  sudo: yes
  template:
    src: .bashrc.j2
    dest: /home/vagrant/.bashrc
    owner: vagrant
    group: vagrant
