# Copyright (C) 2014 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: goran@reciprocitylabs.com
# Maintained By: goran@reciprocitylabs.com

---
ggrc_packages:
  - name: unzip
  - name: zip
  - name: vim
  - name: make
  - name: python-virtualenv
  - name: fabric
  - name: python-mysqldb
  - name: python-imaging
  - name: sqlite3
  - name: python-dev
  - name: nodejs

ggrc_development_directories:
  - name: /vagrant-dev
  - name: /vagrant-dev/opt
  - name: /vagrant-dev/tmp
  - name: /vagrant/tmp

ggrc_databases:
  - name: ggrcdev
  - name: ggrctest
